### PR TITLE
created boss 2 sprite sheet

### PR DESCRIPTION
**Pull request by quample**
sprite sheet of boss 2; contains still assets for 
boss body (with different levels of weapon bay opening), 
energy cells (pristine and destroyed), 
thrusters (pristine and destroyed)

### CODE REVIEW

**Comment by quample** [comment]
fix #73

**Comment by quample** [comment]
@amathur4 just go through the sprites and let me know if these are appropriate for the animations that we discussed.

**Comment by ricardouseche** [comment]
Looks really good. I'll let @amathur4 merge if he gives the OK.

**Review by ricardouseche — COMMENTED** [review]
All good.

**Comment by amathur4** [comment]
The sprite sheet looks good Eljose. I think it looks good to merge with master.

**Review by amathur4 — APPROVED** [review]
Approve boss 2 sprite sheet. How do I merge with master? Ricardo, can you help me with this?

**Comment by ricardouseche** [comment]
@amathur4 for sure. There seems to be a new conflict, so I can fix it before we merge. Basically, you update this branch from master and then the button below will be enabled to merge.

**Pull request merged**
