### PR TITLE
Added thruster animations and fixed sprites Issue#32

### PR DESCRIPTION
**Pull request by amathur4**
Added animations for Blue runner, federation ships, pirate and enemy ships, player ships after performing corrections on sprites for the player ships. Ricardo, please review the request and let me know in case of any modifications.

### CODE REVIEW

**Comment by amathur4** [comment]
fix #issue32

**Comment by ricardouseche** [comment]
@amathur4 These need to be redone with the new, bigger thruster flames, right? Those were merged to master earlier today.

**Comment by amathur4** [comment]
Yes @ricardouseche. The new animations will be required for the bigger thruster flames. I will need the sprites to work on the new animations. Waiting for them.

**Comment by amathur4** [comment]
I just checked the sprite sheets. Are we ready for making animations @ricardouseche ? In that case, I will get started with them and get them ready by tomorrow.

**Comment by ricardouseche** [comment]
All spritesheets are now merged on master. You can start from there 👍

**Pull request closed without merging**
