### PR TITLE
Added sprite sheets for ships

### PR DESCRIPTION
**Pull request by snarla1**

### CODE REVIEW

**Comment by ricardouseche** [comment]
Looks good. Want me to merge and close? @snarla1

**Comment by snarla1** [comment]
> Looks good. Want me to merge and close? @snarla1

Yes, thank you. @ricardouseche

**Comment by ricardouseche** [comment]
@snarla1 Could you also add your .anim files in the PR?

**Comment by snarla1** [comment]
> @snarla1 Could you also add your .anim files in the PR?

Added as said. Could you please take a look at it now? @ricardouseche

**Pull request merged**
