### PR TITLE
Animations

### PR DESCRIPTION
**Pull request by AparnaBudhavarapu**
Added animations for player and pirate ships. Could you please take a look at them and lmk if they look okay. Thanks

### CODE REVIEW

**Comment by ricardouseche** [comment]
Aparna, could you try a few things to solve these merge conflicts? I'm at work and can't access a computer with unity for a while. Try pulling from master, then reopening the project to see if some of these autogen files fix themselves.

**Comment by AparnaBudhavarapu** [comment]
@ricardouseche  the animations that I made are for basic movement, they don't have a proper split for acceleration, idle and deceleration; so we won't be using them. Looks like Aashrit will be incharge of the animations so should I close this merge request and delete the branch?

**Comment by ricardouseche** [comment]
As of now, we also need a frame in your spritesheet where the ships have no fire behind them. Mainly for Pirate_Ship_3 and Pirate_Ship_1. I think you can cut the animations from your PR, but include the new frame in the spritesheet so @amathur4  can make the necessary animations for these ships.

**Comment by AparnaBudhavarapu** [comment]
For the sprite sheets that I made, I already included a frame without fire (player_00, player_01, player_02, enemy_00, enemy_01).  Pirate_Ship_3 and Pirate_Ship_1 were made by srinitya

**Comment by ricardouseche** [comment]
I see now. I'm sorry for the confusion!

I do have one last ask, could you organize the spritesheet frames so that fire increases from right to left? Right now it seems like max fire is at frame 4 instead of the last one. That will just make slicing easier.

image

EDIT: NVM LMAO. I just realized we can use this current 6 frame set up for both acceleration, deceleration and idle!!! Silly me.

**Comment by ricardouseche** [comment]
I fixed the gitignore. I'm gonna restart this pull request and see what happens.

**Pull request closed without merging**
