### PR TITLE
Revised demo scene

### PR DESCRIPTION
**Pull request by mitul323**
Added colliders to limit gamespace. Changed sprites for health & shield bars. Removed starfield.

### CODE REVIEW

**Comment by ricardouseche** [comment]
Scene is looking really good. However, I think this branch was started long before the gitignore changes were done. Could you merge master on to it, or try starting a new branch? Additionally, it seems this changed the version of unity for the project.

**Comment by BenJLubrano** [comment]
The conflicts here are not too bad, mostly auto resolved. However, when I tried to merge it into a local master, I got 53 conflicts in MidtermScene.unity, all of which would have to be manually resolved via text editing...

So here's what I'm going to do: 
Create a local copy of mitul_midtermscene
Duplicate the midtermscene into a new file
Commit

THEN do all of this again, so we will have both the midterm scene from master and the one from mitul_midterm scene. From there, I'll add any missing stuff that people have made recently (In a new branch) and then that will be the final scene we use for the midterm.

Git really does not do a good job with unity if more than one person are working on a scene, so we should really avoid this in the future

**Comment by mitul323** [comment]
I did do an update from master right before committing, I'll check my
version of unity.

**Comment by BenJLubrano** [comment]
Okay, so here's what I ended up doing.

I created a new branch from master called ben_midtermscene
Then, I merged all of the changes from mitul_midtermscene into ben_midtermscene
Then, I merged ben_programming_issue29 (the branch I have been working in for the passed week with the boss fight, etc) into ben_midtermscene

So, what I've ended up with is a branch that contains almost all of the changes from this week that will basically be our midterm build of the game.

mitul_midtermscene will not be merged for this reason, all of the changes in the branch are in ben_midtermscene, so I'll merge that one instead. 

I am closing this PR.

**Pull request closed without merging**
